use crate::models::{AppCategory, AppItem, PackageSource};

pub struct CatalogService;

impl CatalogService {
    pub fn search(query: &str) -> Vec<AppItem> {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return Self::get_all_apps();
        }
        let mut results: Vec<AppItem> = Self::get_all_apps()
            .into_iter()
            .filter(|app| {
                app.name.to_lowercase().contains(&q)
                    || app.package_name.to_lowercase().contains(&q)
                    || app.description.to_lowercase().contains(&q)
                    || app.tags.iter().any(|t| t.to_lowercase().contains(&q))
            })
            .collect();

        results.sort_by(|a, b| {
            let a_exact = a.package_name.to_lowercase() == q || a.name.to_lowercase() == q;
            let b_exact = b.package_name.to_lowercase() == q || b.name.to_lowercase() == q;
            b_exact.cmp(&a_exact)
        });

        results
    }

    pub fn get_all_apps() -> Vec<AppItem> {
        vec![
            // ==========================================
            // --- 1. Temel Uygulamalar (Essentials) ---
            // ==========================================
            AppItem {
                id: "org.gnome.Nautilus".into(),
                name: "Files (Nautilus)".into(),
                package_name: "nautilus".into(),
                description: "GNOME masaüstü için sade ve modern dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.gnome.Nautilus".into(),
                homepage: Some("https://apps.gnome.org/Nautilus/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["file-manager".into(), "gnome".into(), "files".into()],
            },
            AppItem {
                id: "org.kde.dolphin".into(),
                name: "Dolphin File Manager".into(),
                package_name: "dolphin".into(),
                description: "KDE Plasma'nın güçlü ve son derece özelleştirilebilir dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.kde.dolphin".into(),
                homepage: Some("https://apps.kde.org/dolphin/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["file-manager".into(), "kde".into(), "plasma".into()],
            },
            AppItem {
                id: "org.xfce.thunar".into(),
                name: "Thunar".into(),
                package_name: "thunar".into(),
                description: "XFCE masaüstü için hızlı, hafif ve temiz dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.xfce.thunar".into(),
                homepage: Some("https://docs.xfce.org/xfce/thunar/start".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["file-manager".into(), "xfce".into(), "lightweight".into()],
            },
            AppItem {
                id: "org.videolan.VLC".into(),
                name: "VLC Media Player".into(),
                package_name: "vlc".into(),
                description: "Hemen her formatı oynatabilen evrensel açık kaynaklı medya oynatıcı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "vlc".into(),
                homepage: Some("https://www.videolan.org/vlc/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["video".into(), "audio".into(), "player".into()],
            },
            AppItem {
                id: "io.mpv.Mpv".into(),
                name: "MPV Player".into(),
                package_name: "mpv".into(),
                description: "Kusursuz GPU video hızlandırmalı, minimalist ve güçlü medya oynatıcı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "mpv".into(),
                homepage: Some("https://mpv.io/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["video".into(), "media".into(), "minimal".into()],
            },
            AppItem {
                id: "org.keepassxc.KeePassXC".into(),
                name: "KeePassXC".into(),
                package_name: "keepassxc".into(),
                description: "Güvenli, yerel ve çapraz platform şifre yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "keepassxc".into(),
                homepage: Some("https://keepassxc.org/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["password".into(), "security".into(), "privacy".into()],
            },
            AppItem {
                id: "com.bitwarden.desktop".into(),
                name: "Bitwarden".into(),
                package_name: "bitwarden".into(),
                description: "Güvenli ve bulut senkronizasyonlu modern parola kasası.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Aur,
                icon: "bitwarden".into(),
                homepage: Some("https://bitwarden.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["password".into(), "cloud".into(), "security".into()],
            },
            AppItem {
                id: "org.gnome.Evince".into(),
                name: "Document Viewer (Evince)".into(),
                package_name: "evince".into(),
                description: "PDF, PostScript ve benzeri çoklu belge biçimleri için hafif okuyucu.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.gnome.Evince".into(),
                homepage: Some("https://apps.gnome.org/Evince/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["pdf".into(), "reader".into(), "document".into()],
            },
            AppItem {
                id: "org.kde.okular".into(),
                name: "Okular".into(),
                package_name: "okular".into(),
                description: "Evrensel belge inceleme, not ekleme ve PDF görüntüleyici.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "okular".into(),
                homepage: Some("https://okular.kde.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["pdf".into(), "reader".into(), "kde".into()],
            },
            AppItem {
                id: "org.kde.ark".into(),
                name: "Ark".into(),
                package_name: "ark".into(),
                description: "ZIP, TAR, 7Z, RAR arşivlerini görüntüleme ve çıkartma aracı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "ark".into(),
                homepage: Some("https://apps.kde.org/ark/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["archive".into(), "zip".into(), "tar".into()],
            },
            AppItem {
                id: "org.gnome.FileRoller".into(),
                name: "File Roller".into(),
                package_name: "file-roller".into(),
                description: "GNOME masaüstü için pratik arşiv sıkıştırma ve açma yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "file-roller".into(),
                homepage: Some("https://apps.gnome.org/FileRoller/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["archive".into(), "gnome".into(), "zip".into()],
            },

            // ==========================================
            // --- 2. İnternet & Ağ (Internet) ---
            // ==========================================
            AppItem {
                id: "org.mozilla.firefox".into(),
                name: "Mozilla Firefox".into(),
                package_name: "firefox".into(),
                description: "Gizliliğe önem veren, hızlı ve modern açık kaynaklı web tarayıcısı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "firefox".into(),
                homepage: Some("https://www.mozilla.org/firefox/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "web".into(), "privacy".into()],
            },
            AppItem {
                id: "com.brave.Browser".into(),
                name: "Brave Browser".into(),
                package_name: "brave-bin".into(),
                description: "Dahili reklam engelleyici ve izleyici korumalı Chromium tabanlı tarayıcı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "brave-desktop".into(),
                homepage: Some("https://brave.com/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "adblock".into(), "chromium".into()],
            },
            AppItem {
                id: "com.google.Chrome".into(),
                name: "Google Chrome".into(),
                package_name: "google-chrome".into(),
                description: "Google tarafından geliştirilen popüler, hızlı ve güvenli web tarayıcısı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "google-chrome".into(),
                homepage: Some("https://www.google.com/chrome/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["browser".into(), "google".into(), "web".into()],
            },
            AppItem {
                id: "org.chromium.Chromium".into(),
                name: "Chromium".into(),
                package_name: "chromium".into(),
                description: "Açık kaynaklı web tarayıcı projesi (Chrome'un temeli).".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "chromium".into(),
                homepage: Some("https://www.chromium.org/".into()),
                license: Some("BSD-3-Clause".into()),
                tags: vec!["browser".into(), "open-source".into()],
            },
            AppItem {
                id: "io.gitlab.librewolf-community".into(),
                name: "LibreWolf".into(),
                package_name: "librewolf-bin".into(),
                description: "Kullanıcı takibini engelleyen, gizlilik odaklı bağımsız Firefox çatalı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "librewolf".into(),
                homepage: Some("https://librewolf.net/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "privacy".into(), "security".into()],
            },
            AppItem {
                id: "org.torproject.torbrowser".into(),
                name: "Tor Browser".into(),
                package_name: "tor-browser-bin".into(),
                description: "Tor ağı üzerinden tam anonimlik ve gözetim korumalı web gezintisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "tor-browser".into(),
                homepage: Some("https://www.torproject.org/".into()),
                license: Some("BSD-3-Clause".into()),
                tags: vec!["browser".into(), "tor".into(), "privacy".into(), "onion".into()],
            },
            AppItem {
                id: "org.mozilla.thunderbird".into(),
                name: "Thunderbird".into(),
                package_name: "thunderbird".into(),
                description: "E-posta, takvim ve kişi yönetimi sunan gelişmiş iletişim istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "thunderbird".into(),
                homepage: Some("https://www.thunderbird.net/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["mail".into(), "email".into(), "calendar".into()],
            },
            AppItem {
                id: "org.telegram.desktop".into(),
                name: "Telegram Desktop".into(),
                package_name: "telegram-desktop".into(),
                description: "Hızlı, bulut tabanlı ve güvenli anlık mesajlaşma uygulaması.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "org.telegram.desktop".into(),
                homepage: Some("https://desktop.telegram.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["chat".into(), "messenger".into(), "messaging".into()],
            },
            AppItem {
                id: "com.discordapp.Discord".into(),
                name: "Discord".into(),
                package_name: "discord".into(),
                description: "Topluluklar ve oyuncular için sesli, görüntülü ve yazılı sohbet platformu.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "discord".into(),
                homepage: Some("https://discord.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["chat".into(), "voice".into(), "gaming".into()],
            },
            AppItem {
                id: "dev.vencord.Vesktop".into(),
                name: "Vesktop".into(),
                package_name: "vesktop-bin".into(),
                description: "Vencord eklentileriyle güçlendirilmiş, hafif ve optimize Discord istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "vesktop".into(),
                homepage: Some("https://github.com/Vencord/Vesktop".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["discord".into(), "vencord".into(), "chat".into()],
            },
            AppItem {
                id: "org.signal.Signal".into(),
                name: "Signal Desktop".into(),
                package_name: "signal-desktop".into(),
                description: "Uçtan uca şifreli, yüksek güvenlikli özel mesajlaşma uygulaması.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "signal-desktop".into(),
                homepage: Some("https://signal.org/".into()),
                license: Some("AGPL-3.0-only".into()),
                tags: vec!["chat".into(), "privacy".into(), "encryption".into()],
            },
            AppItem {
                id: "org.qbittorrent.qBittorrent".into(),
                name: "qBittorrent".into(),
                package_name: "qbittorrent".into(),
                description: "Reklamsız, hızlı ve gelişmiş açık kaynaklı BitTorrent istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "qbittorrent".into(),
                homepage: Some("https://www.qbittorrent.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["torrent".into(), "download".into(), "p2p".into()],
            },

            // ==========================================
            // --- 3. Geliştirme Araçları (Development) ---
            // ==========================================
            AppItem {
                id: "com.visualstudio.code".into(),
                name: "Visual Studio Code".into(),
                package_name: "visual-studio-code-bin".into(),
                description: "Microsoft'un popüler, eklenti zengini modern kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "com.visualstudio.code.oss".into(),
                homepage: Some("https://code.visualstudio.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["ide".into(), "editor".into(), "code".into(), "dev".into()],
            },
            AppItem {
                id: "com.vscodium.codium".into(),
                name: "VSCodium".into(),
                package_name: "vscodium-bin".into(),
                description: "VS Code'un Microsoft telemetrisi içermeyen, %100 açık kaynaklı derlemesi.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "vscodium".into(),
                homepage: Some("https://vscodium.com/".into()),
                license: Some("MIT".into()),
                tags: vec!["editor".into(), "opensource".into(), "code".into()],
            },
            AppItem {
                id: "com.sublimetext.three".into(),
                name: "Sublime Text".into(),
                package_name: "sublime-text-4".into(),
                description: "Işık hızında açılan, ultra verimli profesyonel metin ve kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "sublime-text".into(),
                homepage: Some("https://www.sublimetext.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["editor".into(), "fast".into(), "code".into()],
            },
            AppItem {
                id: "io.neovim.nvim".into(),
                name: "Neovim".into(),
                package_name: "neovim".into(),
                description: "Vim çatallaması, Lua destekli modern terminal kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "nvim".into(),
                homepage: Some("https://neovim.io/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["terminal".into(), "vim".into(), "editor".into()],
            },
            AppItem {
                id: "com.gitkraken.GitKraken".into(),
                name: "GitKraken".into(),
                package_name: "gitkraken".into(),
                description: "Görsel dal yönetimi ve Git commit geçmişi aracı.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "gitkraken".into(),
                homepage: Some("https://www.gitkraken.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["git".into(), "vcs".into(), "development".into()],
            },
            AppItem {
                id: "io.dbeaver.DBeaver".into(),
                name: "DBeaver Community".into(),
                package_name: "dbeaver".into(),
                description: "Evrensel veritabanı yöneticisi ve SQL istemcisi (PostgreSQL, MySQL, SQLite vb.).".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "dbeaver".into(),
                homepage: Some("https://dbeaver.io/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["database".into(), "sql".into(), "development".into()],
            },
            AppItem {
                id: "com.getpostman.Postman".into(),
                name: "Postman".into(),
                package_name: "postman-bin".into(),
                description: "REST, GraphQL ve SOAP API geliştirme ve test platformu.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "postman".into(),
                homepage: Some("https://www.postman.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["api".into(), "http".into(), "rest".into()],
            },
            AppItem {
                id: "com.docker.cli".into(),
                name: "Docker".into(),
                package_name: "docker".into(),
                description: "Uygulamaları izole konteynerler içinde derleme ve dağıtma motoru.".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "docker".into(),
                homepage: Some("https://www.docker.com/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["container".into(), "devops".into(), "docker".into()],
            },

            // ==========================================
            // --- 4. Oyun & Eğlence (Gaming) ---
            // ==========================================
            AppItem {
                id: "com.valvesoftware.Steam".into(),
                name: "Steam".into(),
                package_name: "steam".into(),
                description: "Proton uyumluluk katmanıyla binlerce Windows ve Linux oyununu oynatabilen platform.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "steam".into(),
                homepage: Some("https://store.steampowered.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["games".into(), "gaming".into(), "store".into(), "proton".into()],
            },
            AppItem {
                id: "com.heroicgameslauncher.hgl".into(),
                name: "Heroic Games Launcher".into(),
                package_name: "heroic-games-launcher-bin".into(),
                description: "Epic Games, GOG ve Amazon Prime oyunlarını Linux'ta çalıştıran açık kaynaklı başlatıcı.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Aur,
                icon: "heroic".into(),
                homepage: Some("https://heroicgameslauncher.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["epic".into(), "gog".into(), "games".into(), "wine".into()],
            },
            AppItem {
                id: "net.lutris.Lutris".into(),
                name: "Lutris".into(),
                package_name: "lutris".into(),
                description: "Tüm video oyun koleksiyonunuzu (Wine, emülatörler, yerel oyunlar) tek çatı altında toplayan menajer.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "lutris".into(),
                homepage: Some("https://lutris.net/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["gaming".into(), "wine".into(), "emulators".into()],
            },
            AppItem {
                id: "com.usebottles.bottles".into(),
                name: "Bottles".into(),
                package_name: "bottles".into(),
                description: "Windows yazılımlarını ve oyunlarını kolayca yapılandırılmış ortamlarda çalıştırın.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Aur,
                icon: "bottles".into(),
                homepage: Some("https://usebottles.com/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["wine".into(), "windows".into(), "gaming".into()],
            },
            AppItem {
                id: "org.libretro.RetroArch".into(),
                name: "RetroArch".into(),
                package_name: "retroarch".into(),
                description: "Konsol oyunları için gelişmiş emülasyon ve retro oyun motoru.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "retroarch".into(),
                homepage: Some("https://www.retroarch.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["emulator".into(), "retro".into(), "gaming".into()],
            },
            AppItem {
                id: "org.prismlauncher.PrismLauncher".into(),
                name: "Prism Launcher".into(),
                package_name: "prismlauncher".into(),
                description: "Minecraft mod paketleri ve çoklu hesap desteği sunan açık kaynaklı başlatıcı.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "prismlauncher".into(),
                homepage: Some("https://prismlauncher.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["minecraft".into(), "gaming".into(), "mods".into()],
            },
            AppItem {
                id: "org.freedesktop.MangoHud".into(),
                name: "MangoHud".into(),
                package_name: "mangohud".into(),
                description: "Oyun içi FPS, sıcaklık, VRAM ve sistem performans göstergesi (Overlay).".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "input-gaming".into(),
                homepage: Some("https://github.com/flightlessmango/MangoHud".into()),
                license: Some("MIT".into()),
                tags: vec!["fps".into(), "overlay".into(), "performance".into()],
            },

            // ==========================================
            // --- 5. Tasarım & Medya (Multimedia) ---
            // ==========================================
            AppItem {
                id: "com.obsproject.Studio".into(),
                name: "OBS Studio".into(),
                package_name: "obs-studio".into(),
                description: "Profesyonel video kaydı, ekran yakalama ve canlı yayın yazılımı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "com.obsproject.Studio".into(),
                homepage: Some("https://obsproject.com/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["streaming".into(), "recording".into(), "video".into()],
            },
            AppItem {
                id: "org.gimp.GIMP".into(),
                name: "GIMP".into(),
                package_name: "gimp".into(),
                description: "Fotoğraf düzenleme ve görsel kompozisyon için açık kaynaklı grafik yazılımı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "org.gimp.GIMP".into(),
                homepage: Some("https://www.gimp.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["graphics".into(), "photo".into(), "image".into()],
            },
            AppItem {
                id: "org.kde.krita".into(),
                name: "Krita".into(),
                package_name: "krita".into(),
                description: "Dijital boyama, illüstrasyon ve 2D animasyon için profesyonel çizim stüdyosu.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "krita".into(),
                homepage: Some("https://krita.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["drawing".into(), "painting".into(), "art".into()],
            },
            AppItem {
                id: "org.inkscape.Inkscape".into(),
                name: "Inkscape".into(),
                package_name: "inkscape".into(),
                description: "SVG tabanlı profesyonel vektörel çizim ve grafik tasarım aracı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "org.inkscape.Inkscape".into(),
                homepage: Some("https://inkscape.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["vector".into(), "svg".into(), "design".into()],
            },
            AppItem {
                id: "org.blender.Blender".into(),
                name: "Blender".into(),
                package_name: "blender".into(),
                description: "Tam özellikli 3D modelleme, render, animasyon ve video düzenleme paketi.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "blender".into(),
                homepage: Some("https://www.blender.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["3d".into(), "render".into(), "animation".into()],
            },
            AppItem {
                id: "org.kde.kdenlive".into(),
                name: "Kdenlive".into(),
                package_name: "kdenlive".into(),
                description: "Çok kanallı, zengin efektli ve güçlü doğrusal olmayan video kurgu programı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "kdenlive".into(),
                homepage: Some("https://kdenlive.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["video".into(), "editor".into(), "montage".into()],
            },
            AppItem {
                id: "org.audacityteam.Audacity".into(),
                name: "Audacity".into(),
                package_name: "audacity".into(),
                description: "Çok kanallı ses kaydı ve profesyonel ses düzenleme programı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "audacity".into(),
                homepage: Some("https://www.audacityteam.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["audio".into(), "sound".into(), "recording".into()],
            },
            AppItem {
                id: "fr.handbrake.ghb".into(),
                name: "HandBrake".into(),
                package_name: "handbrake".into(),
                description: "Açık kaynaklı video format dönüştürücü ve sıkıştırma aracı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "fr.handbrake.ghb".into(),
                homepage: Some("https://handbrake.fr/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["video".into(), "encoder".into(), "transcoder".into()],
            },
            AppItem {
                id: "com.spotify.Client".into(),
                name: "Spotify".into(),
                package_name: "spotify".into(),
                description: "Milyonlarca şarkı ve podcast içeren dijital müzik akış servisi.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Aur,
                icon: "spotify".into(),
                homepage: Some("https://www.spotify.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["music".into(), "audio".into(), "streaming".into()],
            },

            // ==========================================
            // --- 6. Sistem & Donanım (System) ---
            // ==========================================
            AppItem {
                id: "org.alacritty.Alacritty".into(),
                name: "Alacritty".into(),
                package_name: "alacritty".into(),
                description: "Rust ile yazılmış, GPU hızlandırmalı ultra hızlı terminal emülatörü.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "Alacritty".into(),
                homepage: Some("https://alacritty.org/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["terminal".into(), "cli".into(), "rust".into()],
            },
            AppItem {
                id: "net.kovidgoyal.kitty".into(),
                name: "Kitty".into(),
                package_name: "kitty".into(),
                description: "GPU hızlandırmalı, zengin font ve görsel destekli modern terminal.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "kitty".into(),
                homepage: Some("https://sw.kovidgoyal.net/kitty/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["terminal".into(), "gpu".into(), "fast".into()],
            },
            AppItem {
                id: "org.fastfetch.fastfetch".into(),
                name: "Fastfetch".into(),
                package_name: "fastfetch".into(),
                description: "Neofetch benzeri, ultra hızlı C tabanlı sistem bilgi görüntüleme aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "fastfetch".into(),
                homepage: Some("https://github.com/fastfetch-cli/fastfetch".into()),
                license: Some("MIT".into()),
                tags: vec!["system".into(), "fetch".into(), "hardware".into()],
            },
            AppItem {
                id: "io.github.aristocratos.btop".into(),
                name: "Btop".into(),
                package_name: "btop".into(),
                description: "Görsel CPU, bellek, disk ve ağ kullanımını gösteren modern TUI monitörü.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "btop".into(),
                homepage: Some("https://github.com/aristocratos/btop".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["monitor".into(), "cpu".into(), "ram".into()],
            },
            AppItem {
                id: "org.htop.Htop".into(),
                name: "Htop".into(),
                package_name: "htop".into(),
                description: "Etkileşimli süreç yöneticisi ve hafif sistem kaynak takipçisi.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "htop".into(),
                homepage: Some("https://htop.dev/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["process".into(), "monitor".into(), "system".into()],
            },
            AppItem {
                id: "com.teejeetech.timeshift".into(),
                name: "Timeshift".into(),
                package_name: "timeshift".into(),
                description: "Sistem geri yükleme noktaları (RSYNC veya BTRFS anlık görüntüleri) oluşturma aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "timeshift".into(),
                homepage: Some("https://github.com/linuxmint/timeshift".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["backup".into(), "snapshot".into(), "recovery".into()],
            },
            AppItem {
                id: "org.gnome.GParted".into(),
                name: "GParted".into(),
                package_name: "gparted".into(),
                description: "Disk bölümlerini güvenle yeniden boyutlandırma, oluşturma ve biçimlendirme aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "gparted".into(),
                homepage: Some("https://gparted.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["disk".into(), "partition".into(), "storage".into()],
            },
            AppItem {
                id: "com.github.tchx84.Flatseal".into(),
                name: "Flatseal".into(),
                package_name: "flatseal".into(),
                description: "Flatpak uygulamalarının dosya, ağ ve donanım izinlerini yöneten grafik araç.".into(),
                category: AppCategory::System,
                source: PackageSource::Aur,
                icon: "com.github.tchx84.Flatseal".into(),
                homepage: Some("https://github.com/tchx84/Flatseal".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["flatpak".into(), "permissions".into(), "sandbox".into()],
            },
            AppItem {
                id: "org.gnome.DiskUtility".into(),
                name: "GNOME Disks".into(),
                package_name: "gnome-disk-utility".into(),
                description: "SMART sağlık denetimi, disk imajı alma ve sürücü yönetimi.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "gnome-disk-utility".into(),
                homepage: Some("https://apps.gnome.org/DiskUtility/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["disk".into(), "drive".into(), "smart".into()],
            },
        ]
    }
}
