use crate::models::{AppCategory, AppItem, PackageSource};

pub struct CatalogService;

impl CatalogService {
    pub fn search(query: &str) -> Vec<AppItem> {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return Self::get_all_apps();
        }
        let mut results: Vec<AppItem> = Self::get_all_apps()
            .into_iter()
            .filter(|app| {
                app.name.to_lowercase().contains(&q)
                    || app.package_name.to_lowercase().contains(&q)
                    || app.description.to_lowercase().contains(&q)
                    || app.tags.iter().any(|t| t.to_lowercase().contains(&q))
            })
            .collect();

        results.sort_by(|a, b| {
            let a_exact = a.package_name.to_lowercase() == q || a.name.to_lowercase() == q;
            let b_exact = b.package_name.to_lowercase() == q || b.name.to_lowercase() == q;
            b_exact.cmp(&a_exact)
        });

        results
    }

    pub fn get_all_apps() -> Vec<AppItem> {
        vec![
            // ==========================================
            // --- 1. Temel Uygulamalar (Essentials) ---
            // ==========================================
            AppItem {
                id: "org.gnome.Nautilus".into(),
                name: "Files (Nautilus)".into(),
                package_name: "nautilus".into(),
                description: "GNOME masaüstü için sade ve modern dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.gnome.Nautilus".into(),
                homepage: Some("https://apps.gnome.org/Nautilus/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["file-manager".into(), "gnome".into(), "files".into()],
            },
            AppItem {
                id: "org.kde.dolphin".into(),
                name: "Dolphin File Manager".into(),
                package_name: "dolphin".into(),
                description: "KDE Plasma'nın güçlü ve son derece özelleştirilebilir dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.kde.dolphin".into(),
                homepage: Some("https://apps.kde.org/dolphin/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["file-manager".into(), "kde".into(), "plasma".into()],
            },
            AppItem {
                id: "org.xfce.thunar".into(),
                name: "Thunar".into(),
                package_name: "thunar".into(),
                description: "XFCE masaüstü için hızlı, hafif ve temiz dosya yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.xfce.thunar".into(),
                homepage: Some("https://docs.xfce.org/xfce/thunar/start".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["file-manager".into(), "xfce".into(), "lightweight".into()],
            },
            AppItem {
                id: "org.videolan.VLC".into(),
                name: "VLC Media Player".into(),
                package_name: "vlc".into(),
                description: "Hemen her formatı oynatabilen evrensel açık kaynaklı medya oynatıcı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "vlc".into(),
                homepage: Some("https://www.videolan.org/vlc/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["video".into(), "audio".into(), "player".into()],
            },
            AppItem {
                id: "io.mpv.Mpv".into(),
                name: "MPV Player".into(),
                package_name: "mpv".into(),
                description: "Kusursuz GPU video hızlandırmalı, minimalist ve güçlü medya oynatıcı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "mpv".into(),
                homepage: Some("https://mpv.io/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["video".into(), "media".into(), "minimal".into()],
            },
            AppItem {
                id: "org.keepassxc.KeePassXC".into(),
                name: "KeePassXC".into(),
                package_name: "keepassxc".into(),
                description: "Güvenli, yerel ve çapraz platform şifre yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "keepassxc".into(),
                homepage: Some("https://keepassxc.org/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["password".into(), "security".into(), "privacy".into()],
            },
            AppItem {
                id: "com.bitwarden.desktop".into(),
                name: "Bitwarden".into(),
                package_name: "bitwarden".into(),
                description: "Güvenli ve bulut senkronizasyonlu modern parola kasası.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Aur,
                icon: "bitwarden".into(),
                homepage: Some("https://bitwarden.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["password".into(), "cloud".into(), "security".into()],
            },
            AppItem {
                id: "org.gnome.Evince".into(),
                name: "Document Viewer (Evince)".into(),
                package_name: "evince".into(),
                description: "PDF, PostScript ve benzeri çoklu belge biçimleri için hafif okuyucu.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "org.gnome.Evince".into(),
                homepage: Some("https://apps.gnome.org/Evince/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["pdf".into(), "reader".into(), "document".into()],
            },
            AppItem {
                id: "org.kde.okular".into(),
                name: "Okular".into(),
                package_name: "okular".into(),
                description: "Evrensel belge inceleme, not ekleme ve PDF görüntüleyici.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "okular".into(),
                homepage: Some("https://okular.kde.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["pdf".into(), "reader".into(), "kde".into()],
            },
            AppItem {
                id: "org.kde.ark".into(),
                name: "Ark".into(),
                package_name: "ark".into(),
                description: "ZIP, TAR, 7Z, RAR arşivlerini görüntüleme ve çıkartma aracı.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "ark".into(),
                homepage: Some("https://apps.kde.org/ark/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["archive".into(), "zip".into(), "tar".into()],
            },
            AppItem {
                id: "org.gnome.FileRoller".into(),
                name: "File Roller".into(),
                package_name: "file-roller".into(),
                description: "GNOME masaüstü için pratik arşiv sıkıştırma ve açma yöneticisi.".into(),
                category: AppCategory::Essentials,
                source: PackageSource::Official,
                icon: "file-roller".into(),
                homepage: Some("https://apps.gnome.org/FileRoller/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["archive".into(), "gnome".into(), "zip".into()],
            },

            // ==========================================
            // --- 2. İnternet & Ağ (Internet) ---
            // ==========================================
            AppItem {
                id: "org.mozilla.firefox".into(),
                name: "Mozilla Firefox".into(),
                package_name: "firefox".into(),
                description: "Gizliliğe önem veren, hızlı ve modern açık kaynaklı web tarayıcısı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "firefox".into(),
                homepage: Some("https://www.mozilla.org/firefox/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "web".into(), "privacy".into()],
            },
            AppItem {
                id: "com.brave.Browser".into(),
                name: "Brave Browser".into(),
                package_name: "brave-bin".into(),
                description: "Dahili reklam engelleyici ve izleyici korumalı Chromium tabanlı tarayıcı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "brave-desktop".into(),
                homepage: Some("https://brave.com/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "adblock".into(), "chromium".into()],
            },
            AppItem {
                id: "com.google.Chrome".into(),
                name: "Google Chrome".into(),
                package_name: "google-chrome".into(),
                description: "Google tarafından geliştirilen popüler, hızlı ve güvenli web tarayıcısı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "google-chrome".into(),
                homepage: Some("https://www.google.com/chrome/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["browser".into(), "google".into(), "web".into()],
            },
            AppItem {
                id: "org.chromium.Chromium".into(),
                name: "Chromium".into(),
                package_name: "chromium".into(),
                description: "Açık kaynaklı web tarayıcı projesi (Chrome'un temeli).".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "chromium".into(),
                homepage: Some("https://www.chromium.org/".into()),
                license: Some("BSD-3-Clause".into()),
                tags: vec!["browser".into(), "open-source".into()],
            },
            AppItem {
                id: "io.gitlab.librewolf-community".into(),
                name: "LibreWolf".into(),
                package_name: "librewolf-bin".into(),
                description: "Kullanıcı takibini engelleyen, gizlilik odaklı bağımsız Firefox çatalı.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "librewolf".into(),
                homepage: Some("https://librewolf.net/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["browser".into(), "privacy".into(), "security".into()],
            },
            AppItem {
                id: "org.torproject.torbrowser".into(),
                name: "Tor Browser".into(),
                package_name: "tor-browser-bin".into(),
                description: "Tor ağı üzerinden tam anonimlik ve gözetim korumalı web gezintisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "tor-browser".into(),
                homepage: Some("https://www.torproject.org/".into()),
                license: Some("BSD-3-Clause".into()),
                tags: vec!["browser".into(), "tor".into(), "privacy".into(), "onion".into()],
            },
            AppItem {
                id: "org.mozilla.thunderbird".into(),
                name: "Thunderbird".into(),
                package_name: "thunderbird".into(),
                description: "E-posta, takvim ve kişi yönetimi sunan gelişmiş iletişim istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "thunderbird".into(),
                homepage: Some("https://www.thunderbird.net/".into()),
                license: Some("MPL-2.0".into()),
                tags: vec!["mail".into(), "email".into(), "calendar".into()],
            },
            AppItem {
                id: "org.telegram.desktop".into(),
                name: "Telegram Desktop".into(),
                package_name: "telegram-desktop".into(),
                description: "Hızlı, bulut tabanlı ve güvenli anlık mesajlaşma uygulaması.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "org.telegram.desktop".into(),
                homepage: Some("https://desktop.telegram.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["chat".into(), "messenger".into(), "messaging".into()],
            },
            AppItem {
                id: "com.discordapp.Discord".into(),
                name: "Discord".into(),
                package_name: "discord".into(),
                description: "Topluluklar ve oyuncular için sesli, görüntülü ve yazılı sohbet platformu.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "discord".into(),
                homepage: Some("https://discord.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["chat".into(), "voice".into(), "gaming".into()],
            },
            AppItem {
                id: "dev.vencord.Vesktop".into(),
                name: "Vesktop".into(),
                package_name: "vesktop-bin".into(),
                description: "Vencord eklentileriyle güçlendirilmiş, hafif ve optimize Discord istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Aur,
                icon: "vesktop".into(),
                homepage: Some("https://github.com/Vencord/Vesktop".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["discord".into(), "vencord".into(), "chat".into()],
            },
            AppItem {
                id: "org.signal.Signal".into(),
                name: "Signal Desktop".into(),
                package_name: "signal-desktop".into(),
                description: "Uçtan uca şifreli, yüksek güvenlikli özel mesajlaşma uygulaması.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "signal-desktop".into(),
                homepage: Some("https://signal.org/".into()),
                license: Some("AGPL-3.0-only".into()),
                tags: vec!["chat".into(), "privacy".into(), "encryption".into()],
            },
            AppItem {
                id: "org.qbittorrent.qBittorrent".into(),
                name: "qBittorrent".into(),
                package_name: "qbittorrent".into(),
                description: "Reklamsız, hızlı ve gelişmiş açık kaynaklı BitTorrent istemcisi.".into(),
                category: AppCategory::Internet,
                source: PackageSource::Official,
                icon: "qbittorrent".into(),
                homepage: Some("https://www.qbittorrent.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["torrent".into(), "download".into(), "p2p".into()],
            },

            // ==========================================
            // --- 3. Geliştirme Araçları (Development) ---
            // ==========================================
            AppItem {
                id: "com.visualstudio.code".into(),
                name: "Visual Studio Code".into(),
                package_name: "visual-studio-code-bin".into(),
                description: "Microsoft'un popüler, eklenti zengini modern kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "com.visualstudio.code.oss".into(),
                homepage: Some("https://code.visualstudio.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["ide".into(), "editor".into(), "code".into(), "dev".into()],
            },
            AppItem {
                id: "com.vscodium.codium".into(),
                name: "VSCodium".into(),
                package_name: "vscodium-bin".into(),
                description: "VS Code'un Microsoft telemetrisi içermeyen, %100 açık kaynaklı derlemesi.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "vscodium".into(),
                homepage: Some("https://vscodium.com/".into()),
                license: Some("MIT".into()),
                tags: vec!["editor".into(), "opensource".into(), "code".into()],
            },
            AppItem {
                id: "com.sublimetext.three".into(),
                name: "Sublime Text".into(),
                package_name: "sublime-text-4".into(),
                description: "Işık hızında açılan, ultra verimli profesyonel metin ve kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "sublime-text".into(),
                homepage: Some("https://www.sublimetext.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["editor".into(), "fast".into(), "code".into()],
            },
            AppItem {
                id: "io.neovim.nvim".into(),
                name: "Neovim".into(),
                package_name: "neovim".into(),
                description: "Vim çatallaması, Lua destekli modern terminal kod editörü.".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "nvim".into(),
                homepage: Some("https://neovim.io/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["terminal".into(), "vim".into(), "editor".into()],
            },
            AppItem {
                id: "com.gitkraken.GitKraken".into(),
                name: "GitKraken".into(),
                package_name: "gitkraken".into(),
                description: "Görsel dal yönetimi ve Git commit geçmişi aracı.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "gitkraken".into(),
                homepage: Some("https://www.gitkraken.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["git".into(), "vcs".into(), "development".into()],
            },
            AppItem {
                id: "io.dbeaver.DBeaver".into(),
                name: "DBeaver Community".into(),
                package_name: "dbeaver".into(),
                description: "Evrensel veritabanı yöneticisi ve SQL istemcisi (PostgreSQL, MySQL, SQLite vb.).".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "dbeaver".into(),
                homepage: Some("https://dbeaver.io/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["database".into(), "sql".into(), "development".into()],
            },
            AppItem {
                id: "com.getpostman.Postman".into(),
                name: "Postman".into(),
                package_name: "postman-bin".into(),
                description: "REST, GraphQL ve SOAP API geliştirme ve test platformu.".into(),
                category: AppCategory::Development,
                source: PackageSource::Aur,
                icon: "postman".into(),
                homepage: Some("https://www.postman.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["api".into(), "http".into(), "rest".into()],
            },
            AppItem {
                id: "com.docker.cli".into(),
                name: "Docker".into(),
                package_name: "docker".into(),
                description: "Uygulamaları izole konteynerler içinde derleme ve dağıtma motoru.".into(),
                category: AppCategory::Development,
                source: PackageSource::Official,
                icon: "docker".into(),
                homepage: Some("https://www.docker.com/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["container".into(), "devops".into(), "docker".into()],
            },

            // ==========================================
            // --- 4. Oyun & Eğlence (Gaming) ---
            // ==========================================
            AppItem {
                id: "com.valvesoftware.Steam".into(),
                name: "Steam".into(),
                package_name: "steam".into(),
                description: "Proton uyumluluk katmanıyla binlerce Windows ve Linux oyununu oynatabilen platform.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "steam".into(),
                homepage: Some("https://store.steampowered.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["games".into(), "gaming".into(), "store".into(), "proton".into()],
            },
            AppItem {
                id: "com.heroicgameslauncher.hgl".into(),
                name: "Heroic Games Launcher".into(),
                package_name: "heroic-games-launcher-bin".into(),
                description: "Epic Games, GOG ve Amazon Prime oyunlarını Linux'ta çalıştıran açık kaynaklı başlatıcı.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Aur,
                icon: "heroic".into(),
                homepage: Some("https://heroicgameslauncher.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["epic".into(), "gog".into(), "games".into(), "wine".into()],
            },
            AppItem {
                id: "net.lutris.Lutris".into(),
                name: "Lutris".into(),
                package_name: "lutris".into(),
                description: "Tüm video oyun koleksiyonunuzu (Wine, emülatörler, yerel oyunlar) tek çatı altında toplayan menajer.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "lutris".into(),
                homepage: Some("https://lutris.net/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["gaming".into(), "wine".into(), "emulators".into()],
            },
            AppItem {
                id: "com.usebottles.bottles".into(),
                name: "Bottles".into(),
                package_name: "bottles".into(),
                description: "Windows yazılımlarını ve oyunlarını kolayca yapılandırılmış ortamlarda çalıştırın.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Aur,
                icon: "bottles".into(),
                homepage: Some("https://usebottles.com/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["wine".into(), "windows".into(), "gaming".into()],
            },
            AppItem {
                id: "org.libretro.RetroArch".into(),
                name: "RetroArch".into(),
                package_name: "retroarch".into(),
                description: "Konsol oyunları için gelişmiş emülasyon ve retro oyun motoru.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "retroarch".into(),
                homepage: Some("https://www.retroarch.com/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["emulator".into(), "retro".into(), "gaming".into()],
            },
            AppItem {
                id: "org.prismlauncher.PrismLauncher".into(),
                name: "Prism Launcher".into(),
                package_name: "prismlauncher".into(),
                description: "Minecraft mod paketleri ve çoklu hesap desteği sunan açık kaynaklı başlatıcı.".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "prismlauncher".into(),
                homepage: Some("https://prismlauncher.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["minecraft".into(), "gaming".into(), "mods".into()],
            },
            AppItem {
                id: "org.freedesktop.MangoHud".into(),
                name: "MangoHud".into(),
                package_name: "mangohud".into(),
                description: "Oyun içi FPS, sıcaklık, VRAM ve sistem performans göstergesi (Overlay).".into(),
                category: AppCategory::Gaming,
                source: PackageSource::Official,
                icon: "input-gaming".into(),
                homepage: Some("https://github.com/flightlessmango/MangoHud".into()),
                license: Some("MIT".into()),
                tags: vec!["fps".into(), "overlay".into(), "performance".into()],
            },

            // ==========================================
            // --- 5. Tasarım & Medya (Multimedia) ---
            // ==========================================
            AppItem {
                id: "com.obsproject.Studio".into(),
                name: "OBS Studio".into(),
                package_name: "obs-studio".into(),
                description: "Profesyonel video kaydı, ekran yakalama ve canlı yayın yazılımı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "com.obsproject.Studio".into(),
                homepage: Some("https://obsproject.com/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["streaming".into(), "recording".into(), "video".into()],
            },
            AppItem {
                id: "org.gimp.GIMP".into(),
                name: "GIMP".into(),
                package_name: "gimp".into(),
                description: "Fotoğraf düzenleme ve görsel kompozisyon için açık kaynaklı grafik yazılımı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "org.gimp.GIMP".into(),
                homepage: Some("https://www.gimp.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["graphics".into(), "photo".into(), "image".into()],
            },
            AppItem {
                id: "org.kde.krita".into(),
                name: "Krita".into(),
                package_name: "krita".into(),
                description: "Dijital boyama, illüstrasyon ve 2D animasyon için profesyonel çizim stüdyosu.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "krita".into(),
                homepage: Some("https://krita.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["drawing".into(), "painting".into(), "art".into()],
            },
            AppItem {
                id: "org.inkscape.Inkscape".into(),
                name: "Inkscape".into(),
                package_name: "inkscape".into(),
                description: "SVG tabanlı profesyonel vektörel çizim ve grafik tasarım aracı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "org.inkscape.Inkscape".into(),
                homepage: Some("https://inkscape.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["vector".into(), "svg".into(), "design".into()],
            },
            AppItem {
                id: "org.blender.Blender".into(),
                name: "Blender".into(),
                package_name: "blender".into(),
                description: "Tam özellikli 3D modelleme, render, animasyon ve video düzenleme paketi.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "blender".into(),
                homepage: Some("https://www.blender.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["3d".into(), "render".into(), "animation".into()],
            },
            AppItem {
                id: "org.kde.kdenlive".into(),
                name: "Kdenlive".into(),
                package_name: "kdenlive".into(),
                description: "Çok kanallı, zengin efektli ve güçlü doğrusal olmayan video kurgu programı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "kdenlive".into(),
                homepage: Some("https://kdenlive.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["video".into(), "editor".into(), "montage".into()],
            },
            AppItem {
                id: "org.audacityteam.Audacity".into(),
                name: "Audacity".into(),
                package_name: "audacity".into(),
                description: "Çok kanallı ses kaydı ve profesyonel ses düzenleme programı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "audacity".into(),
                homepage: Some("https://www.audacityteam.org/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["audio".into(), "sound".into(), "recording".into()],
            },
            AppItem {
                id: "fr.handbrake.ghb".into(),
                name: "HandBrake".into(),
                package_name: "handbrake".into(),
                description: "Açık kaynaklı video format dönüştürücü ve sıkıştırma aracı.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Official,
                icon: "fr.handbrake.ghb".into(),
                homepage: Some("https://handbrake.fr/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["video".into(), "encoder".into(), "transcoder".into()],
            },
            AppItem {
                id: "com.spotify.Client".into(),
                name: "Spotify".into(),
                package_name: "spotify".into(),
                description: "Milyonlarca şarkı ve podcast içeren dijital müzik akış servisi.".into(),
                category: AppCategory::Multimedia,
                source: PackageSource::Aur,
                icon: "spotify".into(),
                homepage: Some("https://www.spotify.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["music".into(), "audio".into(), "streaming".into()],
            },

            // ==========================================
            // --- 6. Sistem & Donanım (System) ---
            // ==========================================
            AppItem {
                id: "org.alacritty.Alacritty".into(),
                name: "Alacritty".into(),
                package_name: "alacritty".into(),
                description: "Rust ile yazılmış, GPU hızlandırmalı ultra hızlı terminal emülatörü.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "Alacritty".into(),
                homepage: Some("https://alacritty.org/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["terminal".into(), "cli".into(), "rust".into()],
            },
            AppItem {
                id: "net.kovidgoyal.kitty".into(),
                name: "Kitty".into(),
                package_name: "kitty".into(),
                description: "GPU hızlandırmalı, zengin font ve görsel destekli modern terminal.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "kitty".into(),
                homepage: Some("https://sw.kovidgoyal.net/kitty/".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["terminal".into(), "gpu".into(), "fast".into()],
            },
            AppItem {
                id: "org.fastfetch.fastfetch".into(),
                name: "Fastfetch".into(),
                package_name: "fastfetch".into(),
                description: "Neofetch benzeri, ultra hızlı C tabanlı sistem bilgi görüntüleme aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "fastfetch".into(),
                homepage: Some("https://github.com/fastfetch-cli/fastfetch".into()),
                license: Some("MIT".into()),
                tags: vec!["system".into(), "fetch".into(), "hardware".into()],
            },
            AppItem {
                id: "io.github.aristocratos.btop".into(),
                name: "Btop".into(),
                package_name: "btop".into(),
                description: "Görsel CPU, bellek, disk ve ağ kullanımını gösteren modern TUI monitörü.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "btop".into(),
                homepage: Some("https://github.com/aristocratos/btop".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["monitor".into(), "cpu".into(), "ram".into()],
            },
            AppItem {
                id: "org.htop.Htop".into(),
                name: "Htop".into(),
                package_name: "htop".into(),
                description: "Etkileşimli süreç yöneticisi ve hafif sistem kaynak takipçisi.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "htop".into(),
                homepage: Some("https://htop.dev/".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["process".into(), "monitor".into(), "system".into()],
            },
            AppItem {
                id: "com.teejeetech.timeshift".into(),
                name: "Timeshift".into(),
                package_name: "timeshift".into(),
                description: "Sistem geri yükleme noktaları (RSYNC veya BTRFS anlık görüntüleri) oluşturma aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "timeshift".into(),
                homepage: Some("https://github.com/linuxmint/timeshift".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["backup".into(), "snapshot".into(), "recovery".into()],
            },
            AppItem {
                id: "org.gnome.GParted".into(),
                name: "GParted".into(),
                package_name: "gparted".into(),
                description: "Disk bölümlerini güvenle yeniden boyutlandırma, oluşturma ve biçimlendirme aracı.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "gparted".into(),
                homepage: Some("https://gparted.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["disk".into(), "partition".into(), "storage".into()],
            },
            AppItem {
                id: "com.github.tchx84.Flatseal".into(),
                name: "Flatseal".into(),
                package_name: "flatseal".into(),
                description: "Flatpak uygulamalarının dosya, ağ ve donanım izinlerini yöneten grafik araç.".into(),
                category: AppCategory::System,
                source: PackageSource::Aur,
                icon: "com.github.tchx84.Flatseal".into(),
                homepage: Some("https://github.com/tchx84/Flatseal".into()),
                license: Some("GPL-3.0-only".into()),
                tags: vec!["flatpak".into(), "permissions".into(), "sandbox".into()],
            },
            AppItem {
                id: "org.gnome.DiskUtility".into(),
                name: "GNOME Disks".into(),
                package_name: "gnome-disk-utility".into(),
                description: "SMART sağlık denetimi, disk imajı alma ve sürücü yönetimi.".into(),
                category: AppCategory::System,
                source: PackageSource::Official,
                icon: "gnome-disk-utility".into(),
                homepage: Some("https://apps.gnome.org/DiskUtility/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["disk".into(), "drive".into(), "smart".into()],
            },

            // ==========================================
            // --- 7. Sürücüler & Donanım (Drivers) ---
            // ==========================================
            AppItem {
                id: "org.freedesktop.mesa".into(),
                name: "Mesa 3D Graphics".into(),
                package_name: "mesa".into(),
                description: "Açık kaynaklı standart OpenGL ve 3D grafik hızlandırma sürücüleri.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "mesa".into(),
                homepage: Some("https://www.mesa3d.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["driver".into(), "gpu".into(), "opengl".into(), "mesa".into()],
            },
            AppItem {
                id: "org.freedesktop.vulkan.radeon".into(),
                name: "Vulkan AMD Radeon".into(),
                package_name: "vulkan-radeon".into(),
                description: "AMD Radeon GPU'lar için optimize açık kaynaklı Vulkan grafik sürücüsü (RADV).".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "vulkan".into(),
                homepage: Some("https://www.vulkan.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["driver".into(), "amd".into(), "radeon".into(), "vulkan".into()],
            },
            AppItem {
                id: "org.freedesktop.vulkan.intel".into(),
                name: "Vulkan Intel Graphics".into(),
                package_name: "vulkan-intel".into(),
                description: "Intel HD, UHD, Iris ve Arc grafik kartları için Vulkan sürücüsü (ANV).".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "vulkan".into(),
                homepage: Some("https://www.vulkan.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["driver".into(), "intel".into(), "vulkan".into()],
            },
            AppItem {
                id: "com.nvidia.open".into(),
                name: "Nvidia Open Kernel Modules".into(),
                package_name: "nvidia-open".into(),
                description: "Nvidia Turing, Ampere, Ada ve üzeri modern kartlar için resmi açık kaynaklı çekirdek sürücüsü.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "nvidia".into(),
                homepage: Some("https://github.com/NVIDIA/open-gpu-kernel-modules".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["driver".into(), "nvidia".into(), "gpu".into()],
            },
            AppItem {
                id: "com.nvidia.utils".into(),
                name: "Nvidia Utilities & Vulkan".into(),
                package_name: "nvidia-utils".into(),
                description: "Nvidia GPU'lar için kullanıcı alanı kitaplıkları, CUDA ve Vulkan katmanı.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "nvidia".into(),
                homepage: Some("https://www.nvidia.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["driver".into(), "nvidia".into(), "cuda".into()],
            },
            AppItem {
                id: "com.nvidia.dkms".into(),
                name: "Nvidia DKMS Sürücüsü".into(),
                package_name: "nvidia-dkms".into(),
                description: "GeForce GTX 10 (Pascal), GTX 900 (Maxwell) ve özel çekirdekler için dinamik modül derlemeli tescilli Nvidia sürücüsü.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Aur,
                icon: "nvidia".into(),
                homepage: Some("https://www.nvidia.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["driver".into(), "nvidia".into(), "pascal".into(), "maxwell".into(), "dkms".into()],
            },
            AppItem {
                id: "com.nvidia.legacy470".into(),
                name: "Nvidia 470xx Legacy DKMS".into(),
                package_name: "nvidia-470xx-dkms".into(),
                description: "Eski Kepler mimarili (GeForce GTX 600 / 700 serisi) ekran kartları için miras Nvidia sürücüsü.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Aur,
                icon: "nvidia".into(),
                homepage: Some("https://www.nvidia.com/".into()),
                license: Some("Proprietary".into()),
                tags: vec!["driver".into(), "nvidia".into(), "kepler".into(), "legacy".into(), "dkms".into()],
            },
            AppItem {
                id: "com.nvidia.settings".into(),
                name: "Nvidia GPU Denetim Masası".into(),
                package_name: "nvidia-settings".into(),
                description: "Nvidia grafik kartları için resmi grafiksel yapılandırma ve performans yönetim aracı.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "nvidia-settings".into(),
                homepage: Some("https://github.com/NVIDIA/nvidia-settings".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["driver".into(), "nvidia".into(), "settings".into(), "gui".into()],
            },
            AppItem {
                id: "org.pipewire.Pulse".into(),
                name: "PipeWire PulseAudio Server".into(),
                package_name: "pipewire-pulse".into(),
                description: "Yeni nesil, ultra düşük gecikmeli profesyonel Linux ses ve video sunucusu.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "pipewire".into(),
                homepage: Some("https://pipewire.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["audio".into(), "sound".into(), "pipewire".into(), "driver".into()],
            },
            AppItem {
                id: "org.pipewire.WirePlumber".into(),
                name: "WirePlumber Session Manager".into(),
                package_name: "wireplumber".into(),
                description: "PipeWire için modüler ses ve video yönlendirme oturum yöneticisi.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "pipewire".into(),
                homepage: Some("https://pipewire.pages.freedesktop.org/wireplumber/".into()),
                license: Some("MIT".into()),
                tags: vec!["audio".into(), "sound".into(), "pipewire".into()],
            },
            AppItem {
                id: "org.bluez.Service".into(),
                name: "BlueZ Bluetooth Protocol".into(),
                package_name: "bluez".into(),
                description: "Linux çekirdeği için resmi Bluetooth protokol yığını ve donanım sürücüsü.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "bluez".into(),
                homepage: Some("http://www.bluez.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["bluetooth".into(), "wireless".into(), "driver".into()],
            },
            AppItem {
                id: "org.bluez.Utils".into(),
                name: "BlueZ Utilities (bluetoothctl)".into(),
                package_name: "bluez-utils".into(),
                description: "Bluetooth aygıt eşleştirme, yönetme ve kontrol araçları.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "bluez".into(),
                homepage: Some("http://www.bluez.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["bluetooth".into(), "tools".into(), "driver".into()],
            },
            AppItem {
                id: "org.cups.Printing".into(),
                name: "CUPS Printing System".into(),
                package_name: "cups".into(),
                description: "Linux için standart yazdırma sistemi ve çoklu marka yazıcı sürücü motoru.".into(),
                category: AppCategory::Drivers,
                source: PackageSource::Official,
                icon: "cups".into(),
                homepage: Some("https://openprinting.github.io/cups/".into()),
                license: Some("Apache-2.0".into()),
                tags: vec!["printer".into(), "cups".into(), "hardware".into()],
            },

            // ==========================================
            // --- 8. Medya Kodekleri (Codecs) ---
            // ==========================================
            AppItem {
                id: "org.ffmpeg.CLI".into(),
                name: "FFmpeg Universal Media Codecs".into(),
                package_name: "ffmpeg".into(),
                description: "Hemen hemen tüm ses ve video formatlarını çözen evrensel multimedya kütüphanesi.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "ffmpeg".into(),
                homepage: Some("https://ffmpeg.org/".into()),
                license: Some("GPL-3.0-or-later".into()),
                tags: vec!["codec".into(), "video".into(), "audio".into(), "ffmpeg".into()],
            },
            AppItem {
                id: "org.freedesktop.gstreamer.good".into(),
                name: "GStreamer Good Plugins".into(),
                package_name: "gst-plugins-good".into(),
                description: "Açık kaynaklı ve popüler medya formatları için test edilmiş GStreamer kodek seti.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "gstreamer".into(),
                homepage: Some("https://gstreamer.freedesktop.org/".into()),
                license: Some("LGPL-2.1-or-later".into()),
                tags: vec!["codec".into(), "gstreamer".into(), "media".into()],
            },
            AppItem {
                id: "org.freedesktop.gstreamer.bad".into(),
                name: "GStreamer Bad Plugins".into(),
                package_name: "gst-plugins-bad".into(),
                description: "Modern video biçimleri, WebRTC ve ekstra multimedya çözücüleri.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "gstreamer".into(),
                homepage: Some("https://gstreamer.freedesktop.org/".into()),
                license: Some("LGPL-2.1-or-later".into()),
                tags: vec!["codec".into(), "gstreamer".into(), "video".into()],
            },
            AppItem {
                id: "org.freedesktop.gstreamer.ugly".into(),
                name: "GStreamer Ugly Plugins".into(),
                package_name: "gst-plugins-ugly".into(),
                description: "Ticari patent kısıtlı popüler ortam formatları (MP3, DVD vb.) için kodek paketi.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "gstreamer".into(),
                homepage: Some("https://gstreamer.freedesktop.org/".into()),
                license: Some("LGPL-2.1-or-later".into()),
                tags: vec!["codec".into(), "gstreamer".into(), "audio".into(), "mp3".into()],
            },
            AppItem {
                id: "org.freedesktop.gstreamer.libav".into(),
                name: "GStreamer FFmpeg Libav Bridge".into(),
                package_name: "gst-libav".into(),
                description: "FFmpeg çözücü motorunu doğrudan GStreamer medya oynatıcılara bağlayan köprü.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "gstreamer".into(),
                homepage: Some("https://gstreamer.freedesktop.org/".into()),
                license: Some("GPL-2.0-or-later".into()),
                tags: vec!["codec".into(), "ffmpeg".into(), "gstreamer".into()],
            },
            AppItem {
                id: "org.freedesktop.vaapi.intel".into(),
                name: "Intel VA-API Media Driver".into(),
                package_name: "intel-media-driver".into(),
                description: "Intel GPU'lar için donanımsal 4K/8K video çözme ve hızlandırma sürücüsü.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "vaapi".into(),
                homepage: Some("https://github.com/intel/media-driver".into()),
                license: Some("MIT".into()),
                tags: vec!["codec".into(), "hardware-acceleration".into(), "intel".into(), "vaapi".into()],
            },
            AppItem {
                id: "org.freedesktop.vaapi.mesa".into(),
                name: "Mesa VA-API Driver".into(),
                package_name: "libva-mesa-driver".into(),
                description: "AMD Radeon kartlar için VA-API donanım hızlandırmalı video kodlama ve çözme.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "vaapi".into(),
                homepage: Some("https://www.mesa3d.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["codec".into(), "hardware-acceleration".into(), "amd".into(), "vaapi".into()],
            },
            AppItem {
                id: "org.videolan.dav1d".into(),
                name: "dav1d AV1 Video Decoder".into(),
                package_name: "dav1d".into(),
                description: "VideoLAN ve FFmpeg tarafından geliştirilen ultra hızlı AV1 video çözücüsü.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "ffmpeg".into(),
                homepage: Some("https://code.videolan.org/videolan/dav1d".into()),
                license: Some("BSD-2-Clause".into()),
                tags: vec!["codec".into(), "av1".into(), "video".into()],
            },
            AppItem {
                id: "org.videolan.x264".into(),
                name: "x264 H.264 Video Encoder".into(),
                package_name: "x264".into(),
                description: "H.264 / MPEG-4 AVC video akışları için optimize kodlama kitaplığı.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "ffmpeg".into(),
                homepage: Some("https://www.videolan.org/developers/x264.html".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["codec".into(), "h264".into(), "video".into()],
            },
            AppItem {
                id: "org.videolan.x265".into(),
                name: "x265 HEVC Video Encoder".into(),
                package_name: "x265".into(),
                description: "H.265 / HEVC yüksek sıkıştırma verimlilikli video kodlama kitaplığı.".into(),
                category: AppCategory::Codecs,
                source: PackageSource::Official,
                icon: "ffmpeg".into(),
                homepage: Some("https://www.videolan.org/developers/x265.html".into()),
                license: Some("GPL-2.0-only".into()),
                tags: vec!["codec".into(), "hevc".into(), "video".into()],
            },

            // ==========================================
            // --- 9. Çalışma Zamanları (Runtimes) ---
            // ==========================================
            AppItem {
                id: "org.winehq.Wine".into(),
                name: "Wine Compatibility Layer".into(),
                package_name: "wine".into(),
                description: "Windows uygulamalarını ve oyunlarını Linux'ta yerel hızda çalıştırma katmanı.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "wine".into(),
                homepage: Some("https://www.winehq.org/".into()),
                license: Some("LGPL-2.1-or-later".into()),
                tags: vec!["runtime".into(), "wine".into(), "windows".into(), "gaming".into()],
            },
            AppItem {
                id: "org.winehq.Winetricks".into(),
                name: "Winetricks".into(),
                package_name: "winetricks".into(),
                description: "Wine önbelleklerine DirectX, Visual C++ ve Windows bileşenlerini kurma yardımcısı.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "winetricks".into(),
                homepage: Some("https://github.com/Winetricks/winetricks".into()),
                license: Some("LGPL-2.1-or-later".into()),
                tags: vec!["runtime".into(), "wine".into(), "tools".into()],
            },
            AppItem {
                id: "com.feralinteractive.GameMode".into(),
                name: "Feral GameMode".into(),
                package_name: "gamemode".into(),
                description: "Oyun başlatıldığında Linux CPU, GPU ve disk önceliklerini maksimize eden optimizasyon motoru.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "gamemode".into(),
                homepage: Some("https://github.com/FeralInteractive/gamemode".into()),
                license: Some("BSD-3-Clause".into()),
                tags: vec!["runtime".into(), "gaming".into(), "performance".into()],
            },
            AppItem {
                id: "com.valvesoftware.Gamescope".into(),
                name: "Valve Gamescope Compositor".into(),
                package_name: "gamescope".into(),
                description: "Valve'ın SteamOS için geliştirdiği mikro-kompozitör, FSR çözünürlük ölçekleyici ve HDR desteği.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "gamescope".into(),
                homepage: Some("https://github.com/ValveSoftware/gamescope".into()),
                license: Some("BSD-2-Clause".into()),
                tags: vec!["runtime".into(), "gaming".into(), "steam".into()],
            },
            AppItem {
                id: "org.openjdk.Java".into(),
                name: "OpenJDK Java Development Kit".into(),
                package_name: "jdk-openjdk".into(),
                description: "Resmi açık kaynak Java geliştirme ortamı ve Java Sanal Makinesi (JVM).".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "java".into(),
                homepage: Some("https://openjdk.org/".into()),
                license: Some("GPL-2.0-with-classpath-exception".into()),
                tags: vec!["runtime".into(), "java".into(), "dev".into()],
            },
            AppItem {
                id: "org.nodejs.Runtime".into(),
                name: "Node.js JavaScript Runtime".into(),
                package_name: "nodejs".into(),
                description: "Chrome V8 motoru üzerine kurulu asenkron, olay güdümlü JavaScript çalışma ortamı.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "nodejs".into(),
                homepage: Some("https://nodejs.org/".into()),
                license: Some("MIT".into()),
                tags: vec!["runtime".into(), "javascript".into(), "nodejs".into(), "dev".into()],
            },
            AppItem {
                id: "org.python.Language".into(),
                name: "Python 3 Environment".into(),
                package_name: "python".into(),
                description: "Modern, dinamik, temiz ve evrensel Python programlama dili yorumlayıcısı.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "python".into(),
                homepage: Some("https://www.python.org/".into()),
                license: Some("Python-2.0".into()),
                tags: vec!["runtime".into(), "python".into(), "dev".into()],
            },
            AppItem {
                id: "com.microsoft.DotnetSDK".into(),
                name: ".NET Core SDK & Runtime".into(),
                package_name: "dotnet-sdk".into(),
                description: "Microsoft'un açık kaynaklı ve çapraz platform .NET uygulama geliştirme ve çalışma ortamı.".into(),
                category: AppCategory::Runtimes,
                source: PackageSource::Official,
                icon: "dotnet".into(),
                homepage: Some("https://dotnet.microsoft.com/".into()),
                license: Some("MIT".into()),
                tags: vec!["runtime".into(), "dotnet".into(), "csharp".into(), "dev".into()],
            },
        ]
    }
}

/// Önceden hazırlanmış hızlı kurulum paketleri (Curated Bundles)
#[derive(Debug, Clone)]
pub struct PackageBundle {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub icon: &'static str,
    pub package_names: &'static [&'static str],
}

impl CatalogService {
    pub fn get_package_bundles() -> Vec<PackageBundle> {
        vec![
            PackageBundle {
                id: "codecs-pack",
                title: "Medya ve Kodek Paketi",
                description: "Video ve ses dosyalarını (MP4, MKV, AV1, MP3 vb.) sorunsuz oynatmak için gerekli tüm GStreamer ve FFmpeg kodekleri.",
                icon: "media-optical-audio-symbolic",
                package_names: &[
                    "ffmpeg",
                    "gst-plugins-good",
                    "gst-plugins-bad",
                    "gst-plugins-ugly",
                    "gst-libav",
                    "dav1d",
                ],
            },
            PackageBundle {
                id: "gaming-pack",
                title: "Oyun ve Uyumluluk Altyapısı",
                description: "Steam, Epic ve Windows oyunlarını Linux'ta yüksek performansla çalıştırmak için Wine, Mesa, Vulkan, GameMode ve Gamescope.",
                icon: "applications-games-symbolic",
                package_names: &[
                    "wine",
                    "winetricks",
                    "gamemode",
                    "gamescope",
                    "mesa",
                    "vulkan-radeon",
                ],
            },
            PackageBundle {
                id: "audio-hardware-pack",
                title: "Ses ve Donanım Altyapısı",
                description: "Düşük gecikmeli PipeWire ses sunucusu, WirePlumber oturum yöneticisi ve Bluetooth protokol araçları.",
                icon: "multimedia-volume-control-symbolic",
                package_names: &[
                    "pipewire-pulse",
                    "wireplumber",
                    "bluez",
                    "bluez-utils",
                ],
            },
            PackageBundle {
                id: "developer-runtime-pack",
                title: "Geliştirici Çalışma Zamanları",
                description: "Yazılım geliştirme ve script çalıştırma için resmi Python, Node.js, OpenJDK Java ve .NET Core SDK ortamları.",
                icon: "applications-development-symbolic",
                package_names: &[
                    "python",
                    "nodejs",
                    "jdk-openjdk",
                    "dotnet-sdk",
                ],
            },
        ]
    }
}
